### ISSUE TITLE
editorconfig somehow causes default coding system not to be used when gpg files opened using epa

### ISSUE THREAD

**Issue by IvanMalison** [editorconfig/editorconfig-emacs#101]
It took me a while to track this issue down because editorconfig was a very non obvious source for this issue. I looked at the code for a bit and editorconfig definitely does quite a bit with the coding system, but  I wasnt able to track down exactly why this is happening.

**Comment by 10sr** [comment]
Thanks!
I'll look into it.

**Comment by 10sr** [comment]
Sorry I have yet to do so much work on this issue yet, but I recently add a commit to improve the feature about configuring coding systems (#102).
It might be possible that this also fixes this issue, so I'd be glad if you try the latest version... :cake:

**Comment by IvanMalison** [comment]
cool ill try to look when i get a chance

**Comment by 10sr** [comment]
Closing because there are no update recently.
Please feel free to reopen issue if the problem still exists.
