### ISSUE TITLE
Handlebars indentation issues

### ISSUE THREAD

**Issue by breyno127** [editorconfig/editorconfig-emacs#104]
I am working on a project in EmberJS. Originally my handlebars blocks were indented like so...
```handlebars
{{#power-select
  selected=destination
  options=cities
  onchange=(action 'chooseDestination')
  as |name|
}}
  {{name}}
{{/power-select}}
```

Since I have installed editorconfig, my handlebars blocks indent like so by default...

```handlebars
{{#power-select
    selected=destination
    options=cities
    onchange=(action 'chooseDestination')
    as |name|
}}
  {{name}}
{{/power-select}}
```

I am using the default `.editorconfig` generated by `ember-cli`...
```
[*.hbs]
insert_final_newline = false
indent_style = space
indent_size = 2
```
and have editorconfig setup in my initl.el as follows...
```elisp
;; editorconfig
(editorconfig-mode 1)
(add-hook 'editorconfig-custom-hooks
  (lambda (hash) (setq web-mode-block-padding 0)))
```

I would like my handlebars blocks to use the previous indentation style as shown above. Is this something I need to change in my `.editorconfig` or is there some elisp code Im missing in my `init.el`

**Comment by xuhdev** [comment]
Are you using web-mode or a different mode to edit the file?

**Comment by breyno127** [comment]
web-mode

**Comment by breyno127** [comment]
I'm not really sure what I did differently, but the issue does not seem to be present this morning. Possibly I needed to reload my `init.el`? I will close this issue and re-open if the problem crops up again and I can figure out how to reproduce.
