### ISSUE TITLE
Add a mode lighter?

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-emacs#110]
@10sr  Do you think we should add a lighter `"EditorConfig"` or `"EConf"`? I personally prefer the former one. It looks normal to me that each minor mode has a lighter. Users can always diminish the lighter if they want.

**Comment by 10sr** [comment]
On second thought I agree with you! 👍 
I like `"EditorConfig"`  too.

**Comment by xuhdev** [comment]
Closed by cffdf36fdd4ca7934a406ab436b5f9a59a527dc5

**Comment by impaktor** [comment]
Would be nice if this could be turned off , some how. It's taking a lot of mode-line realestate.
