### ISSUE TITLE
editorconfig-indentation-alist: php-mode

### ISSUE THREAD

**Issue by SteveJobzniak** [editorconfig/editorconfig-emacs#116]
Any reason why PHP isn't in the indentation mode list?

Here's what it should look like if you want to add it:
`(php-mode c-basic-offset)`

As per: http://php-mode.sourceforge.net/html-manual/Indentation.html

You would normally also need to override `php-mode-coding-style` and set it to Default (instead of PEAR) whenever you want your own indentation to take effect: https://github.com/ejmr/php-mode/issues/226. But because you're injecting via a hook after the style has already been applied, you're free to override `c-basic-offset` without touching the php style parameter.

**Comment by 10sr** [comment]
> Any reason why PHP isn't in the indentation mode list?

It is because php-mode is a child mode of c-mode!
When editorconfig.el cannot find the indentation definition exactly for current mode, editorconfig.el "goes up" and tries to find definition for one of its parent modes, in this case, c-mode.
And editorconfig.el has a definition of `(c-mode c-basic-offset)`, I think there is no problem in working with php-mode.

> You would normally also need to override php-mode-coding-style...

Thanks for this helpful information! I did not know about that.

My understanding: we should be aware of that, but luckily it does not cause any problems with current editorconfig empl, right?

**Comment by SteveJobzniak** [comment]
@10sr: Oh, that's a clever implementation. So *that* is why EditorConfig works with PHP files anyway. I was wondering how it achieved that.

As for the `php-mode-coding-style`: It causes no problems with EditorConfig, since you inject later. They basically do this at mode startup: "if style is 'pear' (which it is by default), add a c-style called 'pear' and switch to it", and that style contains a `c-basic-offset` value. But since you're hooking later than that, you're welcome to override `c-basic-offset` without any risk.

Note that `php-mode` suggests manually typing "nxml-mode" and "js2-mode" and "web-mode" and then "php-mode" etc, to switch editing styles if you have a document with multiple types of content. And every time you type php-mode, it runs that style injection and resets `c-basic-offset`.

But the good news is, editorconfig runs as a hook when major mode changes, so it re-applies the correct offset every time that happens.

Maybe you want to write down these 2 facts somewhere in the project (a code comment) for your own usage, since it could help with future bugtracking.

**Comment by 10sr** [comment]
Good point!
I think there is no reason that php-mode should not be added, I just added it 👍 

Also I added a brief code comment, and wrote a bit more to the commit comment, which we can find via git-blame ;-)

**Comment by xuhdev** [comment]
Shall we close this issue?

**Comment by SteveJobzniak** [comment]
@10sr @xuhdev

Looks good to me! Let's close the issue. :-)
