### ISSUE TITLE
visit file results in 5+ second delay

### ISSUE THREAD

**Issue by winny-** [editorconfig/editorconfig-emacs#120]
When I disable editorconfig-mode this delay goes away. Is there any way to determine if this is a fs issue or an issue with editorconfig?

**Comment by 10sr** [comment]
Umm... for example, what core library are you using?
Switching core libraries between editorconfig core c and editorconfig-core.el (changing `editorconfig-get-properties-function` value) may help looking into this.
If this is a fs issue, editorconfig-mode should be slow for both cases.

Another idea, how about deleting all lines but `root = true` in `.editorconfig`.
If this is an editorconfig-mode issue, the time taken would get shorter when `.editorconfig` has fewer lines.

**Comment by winny-** [comment]
You were right on the money about the core library. I didn't realize I had installed python-editorconfig package on my Archlinux install (required indirectly by mitmproxy). After uninstalling this package the delay went away. I assume the editorconfig core c is probably faster than the editorconfig-mode's implementation and have since installed the c implementation.

Is it possible to configure editorconfig-mode to only use the built-in implementation in the case I want to reinstall mitmproxy from the Archlinux repositories?

**Comment by 10sr** [comment]
> I had installed python-editorconfig package on my Archlinux install (required indirectly by mitmproxy)

Aha, I see!

editorconfig-mode will always use the built-in library when you add following code to your init.el:

```lisp
(setq editorconfig-get-properties-function 
      'editorconfig-core-get-properties-hash)
```

**Comment by xuhdev** [comment]
@10sr Perhaps this should be added to the doc or somewhere else? Also I think it's better to use a sharp quote, as it is more optimization friendly.

**Comment by 10sr** [comment]
> Perhaps this should be added to the doc or somewhere else? 

Sure! Updated README.
https://github.com/editorconfig/editorconfig-emacs/commit/d237d8b427517ac90a7f4f566b5aa5457f8d6c38

> it's better to use a sharp quote, as it is more optimization friendly

True, but in practice it does not bring so big improvement...
Anyway I used the sharp in that commit 👍

**Comment by winny-** [comment]
Thanks for all your help! This is exactly the solution I am looking for!
