### ISSUE TITLE
editor config not reading from the project .editorconfig

### ISSUE THREAD

**Issue by dagda1** [editorconfig/editorconfig-emacs#125]
I have just installed editor-config emacs with the following configuration:

```
(add-to-list 'load-path "~/.emacs.d/lisp")
(require 'editorconfig)
(editorconfig-mode 1)
```

When I start emacs in a project folder, I get the following error:

> Error (editorconfig): Failed to parse file."/Users/paulcowan/projects/.editorconfig"
> .  Styles will not be applied.

It appears to be looking for .editorconfig in the parent folder.

**Comment by xuhdev** [comment]
Yes, it will look up the parent folder, as well as its folder. The order to apply is top-down. Parents are applied first then the current folder's style is applied to override parent's.

**Comment by dagda1** [comment]
thanks for the reply.   i have an editorconfig file in the project directory. should it not pick that up?

**Comment by xuhdev** [comment]
@dagda1 It should, but there is an error in the syntax. Please post that file.

**Comment by dagda1** [comment]
Here you are:

```
root = true

[*]
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 2
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

[*.js]
indent_style = space
indent_size = 2
trim_trailing_whitespace = false
insert_final_newline = true
max_line_length = f
```

**Comment by xuhdev** [comment]
Is it the contents of `/Users/paulcowan/projects/.editorconfig`? I didn't spot any syntax errors...

**Comment by dagda1** [comment]
yes, that is the contents of the file

**Comment by xuhdev** [comment]
@dagda1 Maybe it's this line `max_line_length = f`. Can you remove it and try again?

**Comment by dagda1** [comment]
Yes the error no longer happens if I remove that line.

Thanks
