### ISSUE TITLE
Jump to .editorconfig

### ISSUE THREAD

**Issue by rgrinberg** [editorconfig/editorconfig-emacs#126]
It would be nice to jump to the currently active .editorconfig file.

**Comment by xuhdev** [comment]
Do you mean adding a command to jump to the closest `.editorconfig` file?

**Comment by rgrinberg** [comment]
Yup

**Comment by 10sr** [comment]
I added a function `editorconfig-find-current-editorconfig` for this and bumped version to 0.7.10 .
Try it!
