### ISSUE TITLE
set fill-column directly, don't call set-fill-column

### ISSUE THREAD

**Issue by jadient** [editorconfig/editorconfig-emacs#130]
using set-fill-column to set the fill-column generates a message.  this is confusing and not really necessary.  don't know if this is the best solution, but how about something like this:

<pre>
(defun editorconfig-set-line-length (length)
  "Set the max line length (`fill-column') to LENGTH."
  (when (and (editorconfig-string-integer-p length)
             (> (string-to-number length) 0))
    (setq fill-column (string-to-number length))))
</pre>

**Comment by xuhdev** [comment]
I guess this has already been fixed in #129 ?
