### ISSUE TITLE
Preserving lisp-indent-offset when indent_size=2 for elisp

### ISSUE THREAD

**Issue by jgkamat** [editorconfig/editorconfig-emacs#137]
Hi! This is mostly a request for comments, more than an actual issue. I'm happy to implement all the changes discussed here, if the maintainers like the idea.

the variable `lisp-indent-offset`, which editorconfig changes, has some unintended side effects. When setting `lisp-indent-offset` alignment is disabled for many cases. For example:

lisp-indent-offset = 2
```
(one two
  (three))
```
lisp-indent-offset = nil
```
(one two
     (three))
```

Because of this, it is impossible to get "default indentation" when using editorconfig's indent_size property, so people are stuck between either not specifying anything, and getting broken alignment. 

I would like to add a new variable to `editorconfig-emacs`, perhaps named `editorconfig-el-use-default` which would control whether `lisp-indent-offset` is set, so that in other editors I get reasonable indentation (indent offset 2) while in emacs, I get default indentation, which is preferred.

I'm imagining this variable would have the following behavior:

Unset (`nil`):
- Nothing would change, behavior exactly the same as now

Set to `t`. 
1.  If `indent_size = 2`, set `lisp-indent-offset` to `nil`, instead of 2
2. If `indent_size = <any other number>`, set `lisp-indent-offset` to the number (behavior as now)

Set to a number (eg: 4)
1. Behavior the same as set to `t`, but the number which get's overriden to `nil` is changed. For example, 4 would become `lisp-indent-offset = 4`. 

Let me know what you think. If people like it, I'll make a PR!

**Comment by xuhdev** [comment]
Good point! I agree that in the world of Emacs, elisp is always supposed to format in a certain way, which editorconfig shouldn't interfere. I would say adding a new option to control whether editorconfig should control the coding style of el files (default is `no`). @10sr what do you think?

**Comment by 10sr** [comment]
Thanks :+1:  @jgkamat 

For me, the behavior seems to be a bit tricky.
I want to know why the value `2` would be treated as special. IMO it would be more straightforward to always set `lisp-indent-offset` to `nil` whatever the `indent_size`'s value is, in the second case for example.

**Comment by jgkamat** [comment]
Hi @10sr,

The use case that I'm imagining is two fold:

1. Allow using editorconfig for things other than `indent_size`, which your approach would cover
2. Allow respecting `indent_size` for people who have non-standard indent-sizes. 

For example, if I'm working on a project which has it's `indent_size` set to 4, I probably want to set my `lisp-indent-offset` to 4 as well, since they requested a indent offset of 4. However, if people set their `indent_size` to 2 (which is the default, when `lisp-indent-offset` is nil), I probably would want to leave my `lisp-indent-offset` to nil, which would give me the `indent_size=2` for most lines, and give me proper alignment for the rest.

In reality though, most elisp projects use a `.dir-locals` instead of an editorconfig anyway (or no equivalent file), so I don't think that this the behavior matters too much. I'd be happy to implement it either way  (setting `lisp-indent-offset` to nil regardless, or only if indent_size is 2), just let me know what makes more sense to you.

**Comment by 10sr** [comment]
See, your first idea would be OK 👌 
I'd appreciate your PR, thanks!

**Comment by lassik** [comment]
Forgive my heresy, but should EditorConfig's indent width actually affect Lisp-family languages at all? I have used various Lisps for more than a decade and I can't recall a single substantial project using anything other than 2-space indents. I have been surprised multiple times that Lisp code is affected by the `indent_size = 4` I have set as a default in my `.editorconfig`.

**Comment by xuhdev** [comment]
@lassik EditorConfig is supposed to work cross editors. If a team uses a specific indentation rule for Lisp, an Emacs developer also need to follow. (Of course, if it's just you, it makes no sense for me to set a different rule.)
