### ISSUE TITLE
format buffer according to .editorconfig

### ISSUE THREAD

**Issue by jxs** [editorconfig/editorconfig-emacs#138]
Hi there,
i made a [function](https://github.com/jxs/emacs.d/blob/master/init.el#L63) to format the buffer according to .editorconfig define values, and used it as post-save-hook 
would that be something helpful to have in the editorconfig-emacs mode?

cheers

**Comment by xuhdev** [comment]
Absolutely.Can you make a PR?

**Comment by jxs** [comment]
sure! :)
[PR](https://github.com/editorconfig/editorconfig-emacs/pull/139)
