### ISSUE TITLE
Editorconfig overwriting values set in dir-locals in emacs26

### ISSUE THREAD

**Issue by jgkamat** [editorconfig/editorconfig-emacs#141]
Hi!

I don't know how much editorconfig can do about this, but I wanted to bring it up.

In emacs 25 and less, editorconfig was applied before any `dir-locals.el`, so any dir-locals file would override editorconfig settings. However, in emacs26 (which is in testing now) this is no longer the case, and dir-locals is overriden by editorconfig.

Ideally editorconfig would have the same behavior across releases, which is why I'm opening this issue.

I tried to bisect this, but I was running into some build issues with some older emacs versions, so I'll try again later. This is probably related to adding new 'dir-locals-2' file support, in emacs26.

I'll try to work on figuring out why this is, ideally I'll have something done before emacs26 is actually released.

Maybe editorconfig could check to see if a `dir-locals` file is present, and (optionally) prevent loading editorconfig settings...

**Comment by jgkamat** [comment]
I've found the change that is responsible for this (I think).

`run-mode-hooks` in emacs25 was:
```
(defun run-mode-hooks (&rest hooks)
  "Run mode hooks `delayed-mode-hooks' and HOOKS, or delay HOOKS.
  ...
this instead of `run-hooks' when running their FOO-mode-hook."
  (if delay-mode-hooks
      ;; Delaying case.
      (dolist (hook hooks)
	(push hook delayed-mode-hooks))
    ;; Normal case, just run the hook as before plus any delayed hooks.
    (setq hooks (nconc (nreverse delayed-mode-hooks) hooks))
    (setq delayed-mode-hooks nil)
    (apply 'run-hooks (cons 'change-major-mode-after-body-hook hooks))
    (run-hooks 'after-change-major-mode-hook)))
```

On emacs 26, it's

```
(defun run-mode-hooks (&rest hooks)
  "Run mode hooks `delayed-mode-hooks' and HOOKS, or delay HOOKS.
  ...
running their FOO-mode-hook."
  (if delay-mode-hooks
      ;; Delaying case.
      (dolist (hook hooks)
	(push hook delayed-mode-hooks))
    ;; Normal case, just run the hook as before plus any delayed hooks.
    (setq hooks (nconc (nreverse delayed-mode-hooks) hooks))
    (setq delayed-mode-hooks nil)
    (apply 'run-hooks (cons 'change-major-mode-after-body-hook hooks))
    (if (buffer-file-name)
        (with-demoted-errors "File local-variables error: %s"
          (hack-local-variables 'no-mode)))
    (run-hooks 'after-change-major-mode-hook)
    (dolist (form (nreverse delayed-after-hook-forms))
      (eval form))
    (setq delayed-after-hook-forms nil)))
```

`hack-local-variables` appears to be the function that sets all dir-local variables, including things set from `dir-locals.el`. 

editorconfig-emacs uses `after-change-major-mode-hook` to set it's variables. Previously, there was no difference between `after-change-major-mode-hook` and `change-major-mode-after-body-hook` other than the order. Now, dir-local variables are set between the invocations. 

I propose that we change the hook editorconfig uses from `after-change-major-mode-hook` to `change-major-mode-after-body-hook`, which solves the issue for me (since dir-locals are set after editorconfig-apply runs). I think that this will result in no changes to the behavior, even on older emacs versions. 

If this dosen't seem like a good idea, I can replace the hook with a customizable variable, so users can choose which hook will run `editorconfig-apply`, but I think that might be overkill.

What are your thoughts? :smile:

**Comment by 10sr** [comment]
Very very thanks for looking into this 👍 

It seems there is no reason not to change into `chagne-major-mode-after-body-hook`.
I'll do it shortly, or I'd really appreciate if you make a PR for this!

**Comment by monnier** [comment]
Side note: this will probably change again with Emacs-30: if we want to make use of the Emacs-30 hook specifically designed for packages like EditorConfig, then we will not be able to provide the exact same priority between EditorConfig and `dir-locals.el` (and file-local variables) on all Emacs versions.
