### ISSUE TITLE
settings not applied in csharp-mode

### ISSUE THREAD

**Issue by doomchild** [editorconfig/editorconfig-emacs#153]
I'm running emacs v25.3, and I installed the plugin like so:

```
(use-package editorconfig
  :ensure t
  :demand t
  :mode ("\\.?editorconfig$" . editorconfig-conf-mode)
  :config
  (setq editorconfig-exec-path "/usr/local/bin/editorconfig")
  (editorconfig-mode 1))
```

When I visit a C# file, I can call `editorconfig-display-current-properties`, and I see the output I expect to see (indent of 2 spaces, for example).  However, when I actually go to insert a new line of code, it's indented 4 spaces, instead.  Here is my project's `.editorconfig` file:

```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[{package.json,*.yml}]
indent_style = space
indent_size = 2

[*.md]
trim_trailing_whitespace = false
```

**Comment by 10sr** [comment]
It seems currently `csharp-mode` is not supported...

https://github.com/editorconfig/editorconfig-emacs/blob/master/editorconfig.el#L128

Your contribution is welcome! Or tell me which variable(s) should be set.

**Comment by doomchild** [comment]
How would I go about figuring out what variable needs to be set?  I'm still pretty new to hacking on emacs stuff.

**Comment by 10sr** [comment]
Without editorconfig what to write to your init.el you when you wanto to configure `csharp-mode` indent size?

**Comment by 10sr** [comment]
Sure!
I added csharp-mode to the list, try after the package is updated 👍
