### ISSUE TITLE
Add support for "unset" property value

### ISSUE THREAD

**Issue by preetpalS** [editorconfig/editorconfig-emacs#156]
On http://editorconfig.org/, it states the following:

> For any property, a value of unset is to remove the effect of that property, even if it has been set before. For example, add indent_size = unset to undefine indent_size property (and use editor default).

Currently the *unset* property value is not highlighted like other property values, it would be better if it were highlighted. Also, I'm not sure if the *unset* property value causes any issues with the built-in core library implemented in Emacs-Lisp (that is used as a fallback when the core executable is not found).

**Comment by xuhdev** [comment]
As long as it passes the core testing, you shouldn't need to worry. I've moved the `unset` paragraph upward.
