### ISSUE TITLE
Indentation requires two <tab> presses in Markdown

### ISSUE THREAD

**Issue by doomchild** [editorconfig/editorconfig-emacs#194]
Using emacs 26.1 on MacOS Mojave (with Editorconfig C Core 0.12.3), I have to press <Tab> twice for the line to be indented the correct 4 spaces in a Markdown file.  Pressing <Tab> once indents three spaces, and the second <Tab> goes forward another space.

Here is what is in my `~/.editorconfig` file:

```
##
# Default project editor config. Any changes to this in a given project should be offered as a pull request back into
# this project.
# See http://editorconfig.org
##

##
# Special property that should be specified at the top of the file outside of any sections. Set to true to stop
# .editorconfig files search on current file.
##
root = true

##
# Configuration for all files.
##
[*]
charset = utf-8

# Line length
max_line_length = 120

# Tab indentation
indent_size = 2
indent_style = space

# Line endings
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

##
# make
##
[Makefile]
indent_style = tab

##
# Markdown
##
[*.{md,markdown}]
indent_size = 4
max_line_length = off

##
# Python
##
[*.py]
indent_size = 4

##
# Files
##
[NAME]
insert_final_newline = false

[VERSION]
insert_final_newline = false
```

And here is how `editorconfig-mode` is setup in emacs:

```
(use-package editorconfig
  :mode ("\\.?editorconfig$" . editorconfig-conf-mode)
  :config
  (setq editorconfig-exec-path "/usr/local/bin/editorconfig")
  (editorconfig-mode 1))
```

Am I missing some configuration somewhere?

**Comment by 10sr** [comment]
I cannot reproduce your problem, I want to know two more things :pray: :

- What markdown major-mode are you using?
- Please paste the result of `describe-editorconfig-properties`

**Comment by doomchild** [comment]
I'm using the `markdown-mode` by Jason R. Blevins from MELPA.

Running `describe-editorconfig-properties` results in the following:

```
# EditorConfig for /Users/doomchild/test.md
charset = utf-8
max_line_length = off
indent_size = 4
indent_style = space
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
tab_width = 4
```

**Comment by 10sr** [comment]
Thanks for your information! 👍 

Is https://github.com/doomchild/.emacs.d the init.el you are currently using?
I cloned this repository and tried, but I cannot reproduce your problem...

While checking, I noticed one thing: when the previous line was indented with 3 spaces, then the next line will be indented with 3 spaces with one TAB press. I think this is the expected behavior.

```
Normal paragraph.

   Indented with 3 spaces
_                             # <- 3 spaces will be inserted when pressing TAB once
```

I have no idea other than this...
If it is not the case, I want to get the minimum steps or configurations to reproduce this issue.

**Comment by doomchild** [comment]
Yeah, that's my current configuration, and it's all up to date.

Here's how I reproduce it consistently.  Starting with the following file:

```markdown
# Thing

1. Something
```

If I put the cursor at the end of the last line and hit `<Enter>`, I get the following (the pipe is the cursor):

```markdown
# Thing

1. Something
|
```

If I then hit `<Tab>`, I get the following:

```markdown
# Thing

1. Something
   |
```

Which is only three spaces.  If I hit `<Tab>` again, I get:

```markdown
# Thing

1. Something
    |
```

Which is four spaces, as I have specified in my `~/.editorconfig` file.

**Comment by 10sr** [comment]
Thanks! I see, this seems not to be a bug! 

When inserting a newline in list text in markdown, the indentation of the second line usually should be at the same level as the one of the first line (or do not indent at all), not the configured indent offset.

For example, commonmark specification says about this as follows:

> The most important thing to notice is that the position of the text after the list marker determines how much indentation is needed in subsequent blocks in the list item. If the list marker takes up two spaces, and there are three spaces between the list marker and the next non-whitespace character, then blocks must be indented five spaces in order to fall under the list item.
https://spec.commonmark.org/0.28/#example-217


EditorConfig sets `tab-width` for `markdown-mode`, but `markdown-mode` just follows this rule and ignores `tab-width` for the first TAB.
So, at least, EditorConfig has nothing more to do for this.

In practice, IMO, for most cases you do not need to set `inden_size` for markdown files.
(If you still want `markdown-mode` to respect `tab-width` for the first indentation, you can request to https://github.com/jrblevin/markdown-mode/issues to add a config for that.)

**Comment by doomchild** [comment]
Thanks a lot for looking into this for me.  So this is a bug in `markdown-mode`, then?

**Comment by 10sr** [comment]
I think it is more like a feature request.

**Comment by doomchild** [comment]
Got it. Thanks for your help, man. I'll close this issue.
