### ISSUE TITLE
How far up does editorconfig-emacs search for .editorconfig

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [editorconfig/editorconfig-emacs#202]
As there usually is no notion of a project in Emacs (correct me if I am wrong about this) I was thinking: "But how does the plugin _know_ where to look for the `.editorconfig` file if my project has multiple subdirectories, which could also have subdirectories?"

I found https://github.com/editorconfig/editorconfig-emacs/issues/125, which seems to indicate, that it only looks in the parent directory.

Does it really only look one directory up, or does it look all the way up to filesystem root? And if it only looks one directory up, how does this support projects with directories, which contain directories, which contain directories (3 levels basically)?

If it does not support arbitrarily nested directories in projects, it would be good to be able to at least specify a global fallback `.editorconfig`, which to use in case no `.editorconfig` could be found in the directory hierarchy.

It would be good to have information about this in the readme file.

**Comment by jgkamat** [comment]
Zelphir Kaltstahl writes:

> Does it really only look one directory up, or does it look all the way up to 
> filesystem root? And if it only looks one directory up, how does this 
> support projects with directories, which contain directories, which contain 
> directories (3 levels basically)?

I regularly use this behavior up to my home directory (where I have a file 
with root=True). I don't see why it wouldn't go further than that though.

> If it does not support arbitrarily nested directories in projects, it would 
> be good to be able to at least specify a global fallback `.editorconfig`, 
> which to use in case no `.editorconfig` could be found in the directory 
> hierarchy.

Just put an .editorconfig at the root of your projects directory, homedir, or 
maybe even the root directory.

> It would be good to have information about this in the readme file.

This is a feature of editorconfig, not neccesarily this plugin. From the 
website:

> When opening a file, EditorConfig plugins look for a file named 
> .editorconfig in the directory of the opened file and in every parent 
> directory. A search for .editorconfig files will stop if the root filepath 
> is reached or an EditorConfig file with root=true is found.

**Comment by xuhdev** [comment]
It will keep searching up, and stops until a `root=true` is encountered or the root of the file system is met.

**Comment by ZelphirKaltstahl** [comment]
Great!

I still think a little note in the readme would be great or maybe a link to the description of the behavior on the editorconfig website, so that the reader of the readme is assured, that this is indeed how also the Emacs package works.

Thanks for answering this concern!

**Comment by 10sr** [comment]
The editorconfig website has this paragraph, and IMO it should be enough.

https://editorconfig.org/

> Where are these files stored?
> When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

**Comment by ZelphirKaltstahl** [comment]
I am not debating what the editorconfig page says or does not say and any more quotations of it wont add anything to this topic.

Just put yourself in the shoes of someone checking this repository for a moment. At least I was skeptical about how far the package complies with the standard (being whatever editorconfig page says). As a potential user, I want to read whether the package actually complies with the "no matter how far up your file is, it will be used" policy (or whatever that is called). I want to read how much compliant with the standard the package is, whether it is really an "install and be done with it" package for the purpose. Whether it really implements all that is needed. If I do not read something like this, my doubts about the package come up. People are not all the same and even if you personally do not think that this doubt can come up, I only need one counter example (me) to prove this assertion wrong.

You can either leave users in the dark about this, or you could simply add a line like: _"This package complies with all of the editorconfig standards."_ or _"This package complies with all of the editorconfig standards, except for …"_. It can only help to be very clear about this in your readme file.

Here is another example: If you look up for example some markdown parsers for various languages, you will often find a paragraph or more about how compliant they are with things like Commonmark and in what cases they deviate and why or you will find the percentage in tests passing or failing.
