### ISSUE TITLE
Global fallback .editorconfig

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [editorconfig/editorconfig-emacs#203]
Is there a way to specify a global fallback `.editorconfig` in case that no `.editorconfig` was found in a directory?

This can be useful. For example I have a machine I use at the job and one machine I use at home. In both I could specify different global `.editorconfig`files. At the job there are coding conventions, which I am to follow, so it makes sense to have one config for all work projects, instead of having the same config in every single project.

**Comment by cxw42** [comment]
Related to editorconfig/editorconfig#408

**Comment by jgkamat** [comment]
Zelphir Kaltstahl writes:

> This can be useful. For example I have a machine I use at the job and one 
> machine I use at home. In both I could specify different global 
> `.editorconfig`files. At the job there are coding conventions, which I am to 
> follow, so it makes sense to have one config for all work projects, instead 
> of having the same config in every single project.

Can't you specify a editorconfig in your home (or root) directory that 
reflects the different coding conventions? An emacs-specific variable wouldn't 
help too much as it would only take effect in Emacs.

If all your work code lives in a sub-directory of home, just put a 
.editorconfig file there with root=True.

**Comment by xuhdev** [comment]
Yes, I agree @jgkamat 's solution is the most elegant solution.

**Comment by ZelphirKaltstahl** [comment]
Ah if that is the behavior of this package then nevermind. This is what I hoped the package would do and only asked for a fallback, in case this is not how the package works.

Then I guess this is solved!

**Comment by masaeedu** [comment]
@jgkamat This is a good solution when it works, but unfortunately not everyone stores all of their code in the home folder. This is more a problem with the editorconfig spec than any particular implementation of it though; the mechanism for resolving applicable editorconfigs needs to be decoupled from directory structure.
