### ISSUE TITLE
How to have default settings

### ISSUE THREAD

**Issue by noctuid** [editorconfig/editorconfig-emacs#214]
Right now, I'm using hooks to set defaults for certain file types (e.g. `indent-tabs-mode`). I want them to be defaults, but they overwrite the editorconfig settings since they happen afterwards.

I could have a root editorconfig file with defaults instead, but since scripts without extensions (but with shebangs) aren't supported by editorconfig, this doesn't work well.

Any suggestions?

**Comment by 10sr** [comment]
How about adding a function to `editorconfig-hack-properties-functions`?
This function should check PROD and set the default value only when it was not set yet.
It might not be a perfect solution because you need to write some code, but I think it meets your needs anyway.

**Comment by noctuid** [comment]
> editorconfig-hack-properties-functions

Does this have any effect if there is no .editorconfig file or if the current file does not match something in the .editorconfig file? Does it apply for any opened file? If not, then it has the same issue.

**Comment by 10sr** [comment]
Yes, this hook requires only that editorconfig-mode is enabled (or running editorconfig-apply manually) 👍

**Comment by noctuid** [comment]
Okay thanks, I'll do that. At least until editorconfig properly supports shebangs. Will reopen if I have any issues.
