### ISSUE TITLE
Documentation request to help bootstrap users

### ISSUE THREAD

**Issue by whitty** [editorconfig/editorconfig-emacs#218]
Firstly - thanks this looks like an excellent project.

## Background

The readme file in github describes how to install and customise the plugin, but nothing about how it should _behave_.

I removed my existing `.emacs` code that did path-based matching for style,  installed the plugin and enabled the global mode.

Nothing happened except for `EditorConfig` in the modeline.  I didn't know if this was the correct behaviour or not.  My styles were not applied (C mode).

I tried toggling `editorconfig-mode` in my buffer, nothing.  Eventually I found a bug report where they mentioned `editorconfig-apply` and this actually applied the settings, which I could add to my hooks to get it working.

I'm not sure if `editorconfig-apply` is supposed to be required, or means there's some problem - hence this question about documentation. 

## Issue

Could you please add any of the following that are applicable to the readme.md
* an indication of what `editorconfig-mode` does (and does not do)
   * an indication of "how you would know its working"
   * an indication of what to do if its not working
* if `editorconfig-mode` on its own is not sufficient - a discussion of `editorconfig-apply` and how it should be used
* list of supported packages - if packages need specific support (maybe that's my problem)
* a recommendation to run `editorconfig /path/to/file` to check configuration

**Comment by apiraino** [comment]
The above suggestion is [referenced here](https://github.com/editorconfig/editorconfig-emacs/issues/217#issuecomment-591456779). Thanks @whitty, you helped me make the package work :-)

**Comment by 10sr** [comment]
Sorry for this late response, and thanks for your suggention!

First, normally you don't have to do something about `editorconfig-apply`. Enabling `editorconfig-mode` should be enough for this plugin to work, so it seems to be a bug.
`M-x editorconfig-display-current-properties` can be used to check if properties are successfully loaded.
I'll add these things to README shortly...

**Comment by whitty** [comment]
Thanks - looks good - I can't reproduce the problems I was having.

I really don't know what the issue might have been.

The troubleshooting section is particularly useful.

**Comment by 10sr** [comment]
Thanks! 
Closing this for now, please don't hesitate to reopen if you find anything about this issue 🙌
