### ISSUE TITLE
Editorconfig not applied

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [editorconfig/editorconfig-emacs#229]
I have a JSON file which is:

``` json
{
    "name": "minimal-js-framework",
    "version": "0.0.1",
    "description": "a minimalistic js framework",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [
        "minimalistic",
        "js",
        "framework",
        "component"
    ],
    "author": "Zelphir Kaltstahl",
    "license": "AGPL-3.0-or-later"
}
```

In the same directory I have an `.editorconfig` file:

``` conf
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# Matches multiple files with brace expansion notation
# Set default charset
[*.{js}]
charset = utf-8
indent_size = 2
indent_style = space

# 4 space indentation
[*.py]
charset = utf-8
indent_size = 4
indent_style = space

# Tab indentation (no size specified)
[Makefile]
indent_style = tab
```

When I run `editorconfig-find-current-editorconfig` I get the `.editorconfig` from the same directory opened in a buffer, so it definitely finds that config.

When I run `editorconfig-display-current-properties`, it shows in a buffer:

```
# EditorConfig for /home/user/development/JavaScript/minimal-js-framework/package.json
end_of_line = lf
insert_final_newline = true
```

Which should be different per my settings in the editorconfig file.

In my `.init.el` file I have added:

``` elisp
;; ============
;; EDITORCONFIG
;; ============

;; Editorconfig uses a standardized configuration file to
;; unify formatting across editors, which have support for
;; editorconfig, usually via some plugin or extension.

(require 'editorconfig)
(editorconfig-mode 1)
```

When I try to indent inside my `package.json` file, it stays indented at `4` spaces instead of `2`, as configured in my editorconfig file.

What am I doing wrong?

**Comment by 10sr** [comment]
It seems there is no config for JSON files... 🤔 
I think `[*.{js}]` should be `[*.{js,json}]`.

**Comment by ZelphirKaltstahl** [comment]
Oh my … Thanks for pointing out the mistake!

I must have been config-blind after wasting hours with configs of other tools. The only explanation I have for being so blind.
