### ISSUE TITLE
Maybe use `editorconfig-get-properties` per default

### ISSUE THREAD

**Issue by leotaku** [editorconfig/editorconfig-emacs#230]
According to the documentation, the `editorconfig-get-properties` function tries to use the Editorconfig executable when it is available and otherwise falls back to the Elisp implementation. This seems like the most reasonable default behavior for almost all users. However, currently we use `editorconfig-core-get-properties-hash` per default, so users have to manually configure `editorconfig-emacs` when they want to use the ostensibly faster and more feature-complete C implementation.

Is there any reason we would not want `editorconfig-get-properties` as the default?

**Comment by 10sr** [comment]
Previously it was the default, but I changed this to `editorconfig-core-get-properties-hash` (see #198).
I want to hear @xuhdev's opinion, too, but I think it has these advantages:

- Faster and more secure
- Without config users will use the same core, which makes it easier for us to debug user issues

**Comment by leotaku** [comment]
If the Elisp implementation is in fact faster and more or less feature-complete I of course agree that it should be the default.

I think I last read this repositories README when it still contained information about installing a core program, which made me think that doing so was somehow beneficial.
