### ISSUE TITLE
max_line_length also sets a ruler?

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-emacs#239]
The Vim plugin [allows a setting that shows the column bar at max_line_length](https://github.com/editorconfig/editorconfig-vim/blob/047c4b455b9d56adee63a52d6d7cdf5bb6521d53/doc/editorconfig.txt#L125). @10sr Do you think it makes sense to also have the emacs extension to have this feature for `set-fill-column`?

**Comment by 10sr** [comment]
Emacs>=27.1 provides `display-fill-column-indicator-mode` function, which shows ruler in current buffer.
I think it is nice idea to add an option to enable this when `max_line_length` is set! 🙆

**Comment by jcs090218** [comment]
I think this feature is implemented? If true, then we should just close this. :)

**Comment by 10sr** [comment]
👍 
We can just enable `display-fill-column-indicator-mode` to achieve this!
