### ISSUE TITLE
Always prompt when exit Emacs with recentf-mode on after update

### ISSUE THREAD

**Issue by dalu98** [editorconfig/editorconfig-emacs#240]
After updating to the latest version ee98f3a, I always encountered a prompt problem when exiting Emacs with `recentf-mode` on.

I have tested it in a minimal config (which will be save as `init-mini.el`) as follows:

```elisp
(setq package-archives
      '(("gnu"   . "http://elpa.gnu.org/packages/")
        ("melpa" . "http://melpa.org/packages/")))

(package-initialize)

;; recentf here
(require 'recentf)
(recentf-mode +1)

;; editorconfig here
(editorconfig-mode 1)
```

And here is the steps that can reproduce it:

1. `emacs -Q -l init-mini.el`
2. install `editorconfig` from melpa
3. Restart Emacs and skim through some files to make `~/.emacs.d/recentf` not empty
4. Press <kbd>C-x C-c</kbd> to quit Emacs and a prompt will appear `Revert buffer from file /Users/dalu/.emacs.d/recentf? (yes or no)`
5. If I comment `(editorconfig-mode 1)` and the prompt will disappear, and `recentf` works as I expected.

Is this a bug or had I did something wrong? Thanks!

**Comment by dalu98** [comment]
Fixed, thanks!

**Comment by 10sr** [comment]
Thanks for reporting the issue! 🙆‍♂️
