### ISSUE TITLE
editorconfig-mode-apply runs multiple times for each file

### ISSUE THREAD

**Issue by ambihelical** [editorconfig/editorconfig-emacs#244]
Not sure if this related to #242.  I noticed some severe performance issues with a recent update, especially since I'm letting editorconfig run over tramp ssh.  Each time I open a file editorconfig-mode-apply is running 6 times on each file.   This does a directory walk to the root each time and one traversal is slow but bearable. Six times is so slow I've had to resort to dir-locals like some kind of barbarian.

**Comment by 10sr** [comment]
I started testing a new implementation of editorconfig-mode, in hope that the issue reported in #242, #244 and #246 would be solved.
This can be enabled by setting `(setq editorconfig--enable-20210221-testing t)` before enabling editorconfig-mode.

It is not so tested very well yet, but currently I'm using this impl several days without any problem. 
If you are ok with it, I'd be very glad if you try this new version and see if it works better.
Thanks!

**Comment by 10sr** [comment]
I just merged #263 so this is now enabled by default 🙌 (set editorconfig--legacy-version to disable this and use old version)

**Comment by 10sr** [comment]
Closing this now.
Please reopen this issue if the problem still exists, thanks!
