### ISSUE TITLE
Relicense to GPLv3+

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-emacs#25]
This Emacs plugin has been distributed under a 2 clause BSD license for a long time, which violates the license of Emacs (GPL v3+). However, contribution from multiple people have been included in this project, hereby we must ask everyone who has made nontrivial contribution for the permission to relicense this project. If you agree with the relicensing, (a) if you have a PGP key, please send a signed message with the following text to editorconfig@googlegroups.com (no subscription required) (b) otherwise reply here with the following text:

> Subject: My permission to license all my contribution to EditorConfig Emacs plugin to GNU General Public License version 3 or later
>
> I agree to license all of my contribution to EditorConfig Emacs Plugin (https://github.com/editorconfig/editorconfig-emacs#readme) under the GNU General Public License version 3 or any later version.
> signed-off-by: Your Name < you@example.com > 

Please note that this is a requirement for us to keep your contribution included; see the GPL FAQ [here](https://www.gnu.org/licenses/gpl-faq.html#IfInterpreterIsGPL) and [here](https://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins) if you are still unsure. [RMS has also mentioned Emacs plugins must be released under GPL](https://lists.gnu.org/archive/html/emacs-devel/2015-01/msg00398.html).

@xuhdev @treyhunner @johan @stevejordan @dochang @milkypostman @tarsius

**Comment by tarsius** [comment]
I agree to license all of my contribution to EditorConfig Emacs Plugin (https://github.com/editorconfig/editorconfig-emacs#readme) under the GNU General Public License version 3 or any later version.
signed-off-by: Jonas Bernoulli <jonas@bernoul.li>

**Comment by dochang** [comment]
I agree to license all of my contribution to EditorConfig Emacs Plugin (
https://github.com/editorconfig/editorconfig-emacs#readme) under the GNU
General Public License version 3 or any later version.
signed-off-by: ZHANG Weiyi <dochang@gmail.com>

**Comment by treyhunner** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I agree to license all of my contribution to EditorConfig Emacs Plugin (
https://github.com/editorconfig/editorconfig-emacs#readme) under the GNU
General Public License version 3 or any later version.
signed-off-by: Trey Hunner <trey@treyhunner.com>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVBd68AAoJEOpnfp/NreonG8QIAJRhqJu7gLad0X/Df9jj1wBS
6p3spRRw1xamRKfF33RQ4yzV1Vw0VoAeyS24lqV91cMxZocq+ozspz7rDi+lNTgZ
ro6uBhZ7ZgN0t3TVH3QBjQNdqMkU/hhJnChrTnlnOepe9m+UtdIymdo85/LnZNHN
jJ8Zs18B6MbyKYjk8uiSyadznS/AlXYIDXdWED9u23VkfLxfoi0RRBMrkQ4r5oHX
AT31gHQ2OXjaQiKTUtkwbsE1PHBQMwOZhmEpUM8ZvxswVxJZXBgdvk8k9sqJCIYa
P/N4E3aFaMwUwdDMvy3BG3RQ/VwtUVzLnbs5QyoWcAJBJi8v4skqCKqYxkXtAP0=
=rOKn
-----END PGP SIGNATURE-----
```

**Comment by johan** [comment]
I agree to license all of my contribution to EditorConfig Emacs Plugin (https://github.com/editorconfig/editorconfig-emacs#readme) under the GNU General Public License version 3 or any later version.
signed-off-by: Johan Sundström <oyasumi@gmail.com>

**Comment by stevejordan** [comment]
I agree to license all of my contribution to EditorConfig Emacs Plugin (https://github.com/editorconfig/editorconfig-emacs#readme) under the GNU General Public License version 3 or any later version.

signed-off-by: Steve Jordan <steve@stevejordandigital.co.uk>

**Comment by milkypostman** [comment]
I agree to license all of my contribution to EditorConfig Emacs Plugin (https://github.com/editorconfig/editorconfig-emacs#readme) under the GNU General Public License version 3 or any later version.
signed-off-by: Donald Curtis <d@milkbox.net>

**Comment by xuhdev** [comment]
Thanks, everyone! Done in 81df05486773e42e39d9f137ed1ce7e6b65dcbed
