### ISSUE TITLE
Mentioning NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [editorconfig/editorconfig-emacs#257]
Hi, this is less of an issue, more of a notification:

I just added editorconfig to [NonGNU ELPA](http://elpa.nongnu.org/), the new package archive added to Emacs 28 for external packages: http://elpa.nongnu.org/nongnu/editorconfig.html

In principle this shouldn't affect development. The main difference to MELPA is that stable tags are distributed by default, and these are identified whenever a commit bumps the version tag. From what I see this is already being done, so there should be no issue there.

If you are interested, you could add the NonGNU badge to the README file:

![NonGNU ELPA](http://elpa.nongnu.org/nongnu/editorconfig.svg)

**Comment by 10sr** [comment]
Thanks! I'll check later 🙌
