### ISSUE TITLE
Set indent for evil mode

### ISSUE THREAD

**Issue by jupl** [editorconfig/editorconfig-emacs#26]
Evil (vim in Emacs) includes vim's shifting features. It would be great if the shifting would be set automatically. It would be as simple as a line like this:

```elisp
(setq-local evil-shift-width #INDENT_SIZE#)
```

**Comment by xuhdev** [comment]
LGTM. would you mind making a pull request?

**Comment by jupl** [comment]
Added a PR #30. Let me know if there is anything else I can do to help get this merged.
