### ISSUE TITLE
Ignoring config when using multiple matches with a single extension

### ISSUE THREAD

**Issue by esnunes** [editorconfig/editorconfig-emacs#267]
Using the following config, the plugin is ignoring the Ruby-specific config (`[*.{rb}]`) and it is defaulting to the catch all config (`[*]`):

```editorconfig
root = true

[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8

[*.{rb}]
indent_style = space
indent_size = 2
tab_width = 2
trim_trailing_whitespace = true
```

I've noticed the issue because it was not trimming trailing whitespaces. In order to be sure, I've executed the function `editorconfig-display-current-properties`.

It does work when I remove the multiple matches syntax and use just `[*.rb]`.

**Comment by 10sr** [comment]
Sorry for this late response.

This behavior is intended .
Other EditorConfig plugins works in the same way, and this is also consistent with the glob expansion in unix shells:

```
$ echo a.{rb,txt}
a.rb a.txt
$ echo a.{rb}
a.{rb}
```

You should just write `*.rb` for this case 🎁

**Comment by esnunes** [comment]
Thanks @10sr! I didn't know about this!
