### ISSUE TITLE
editorconfig package missing from MELPA?

### ISSUE THREAD

**Issue by glyn** [editorconfig/editorconfig-emacs#284]
The README says to install "This package", but when I try:
```
M-x install-package
editorconfig
```
emacs prompts me to complete the package name to one of the following:
* editorconfig-charset-extras
* editorconfig-domain-specific
* editorconfig-custom-majormode
* editorconfig-generate

`M-x list-packages` shows these packages are coming from MELPA:
<img width="982" alt="Screenshot 2022-12-21 at 11 53 06" src="https://user-images.githubusercontent.com/94953/208899344-8b9f8094-1e65-4d2a-96dc-1cce0ffa568b.png">

Checking the link to MELPA and the recipe there, it certainly seems as if the package name I should install is "editorconfig".

I tried running `M-x package-refresh-contents`, but the package still wasn't found.

I am running emacs 28.2 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559))
 of 2022-09-12 on macOS 12.6.1 on a Macbook Air M1.

**Comment by jcs090218** [comment]
Is still there. See https://melpa.org/#/editorconfig. It could be something wrong on the MELPA side? 😕

**Comment by glyn** [comment]
Perhaps. I tried enabling MELPA stable too, but editorconfig is still not found.

**Comment by jcs090218** [comment]
Did it show any errors? Do you have it already installed?

**Comment by glyn** [comment]
No, there were no errors. No, it's not already installed.

**Comment by jcs090218** [comment]
If the issue persist, I recommend you to report this issue to upstream MELPA. They might have thoughts about it?

**Comment by glyn** [comment]
Done, thanks ☝️ .

**Comment by glyn** [comment]
I found a workaround for installing editorconfig from MELPA: https://github.com/melpa/melpa/issues/8331#issuecomment-1363731147. The problem seems to be an issue in the UI to MELPA, so let's track that under the MELPA issue.

**Comment by 10sr** [comment]
Sorry to be late to respond. Thanks really for reporting the issue!

**Comment by jcs090218** [comment]
Hi, @10sr! Are you the only active maintainer now? If yes, I volunteer to co-maintain this package! Maybe answer questions, fix minor issues, etc. 

Let me know what you think. Thanks!

**Comment by xuhdev** [comment]
@jcs090218 We certainly need additional maintainers and appreciate your help :) You can start off by contributing PRs and help review PRs. Once you become familiar with the codebase, we are happy to give you additional permission to the repo. @10sr Does it sound good for you?

**Comment by jcs090218** [comment]
> We certainly need additional maintainers and appreciate your help :) You can start off by contributing PRs and help review PRs. Once you become familiar with the codebase, we are happy to give you additional permission to the repo.

Sounds good to me! :)

> `@10sr` Does it sound good for you?

It would be great if we have your permission!

**Comment by 10sr** [comment]
@jcs090218 @xuhdev Great idea! Of course I'm OK with it, thanks 🙆‍♂️
