### ISSUE TITLE
respscts `[Makefile]` but not `[{Makefile}]`

### ISSUE THREAD

**Issue by mmahmoudian** [editorconfig/editorconfig-emacs#315]
First and foremost, thanks for maintaining this package.

I was hitting my head against the wall to debug a Makefile that ultimately I realized one of the lines has space indentation instead of tab. The following is my

```editorconfig
root = true

[*]
indent_style = space
indent_size  = 4
charset = utf-8
insert_final_newline = true

[{Makefile}]
indent_style = tab
indent_size  = 4
insert_final_newline = true
```

The following is the output of `editorconfig-display-current-properties`:

```editorconfig
# EditorConfig for /home/mehrad/<<redacted>>/Makefile
indent_style = space
indent_size = 4
charset = utf-8
insert_final_newline = true
tab_width = 4
```

But when I change `[{Makefile}]` to `[Makefile]` the `editorconfig-display-current-properties` shows:

```editorconfig
# EditorConfig for /home/mehrad/<<redacted>>/Makefile
indent_style = tab
indent_size = 4
charset = utf-8
insert_final_newline = true
tab_width = 4
```

I checked the [specification of the EditorConfig](https://spec.editorconfig.org/) and I cannot find any restrictions to not to treat `[{filename}]` as correct syntax.

**Comment by xuhdev** [comment]
`[{Makefile}]` only matches `{Makefile}` literally. The spec doesn't make it clear, but the test has already enforced it:

- https://github.com/editorconfig/editorconfig-core-test/blob/5ca0b296dc31124d0303895c163013450bd97958/glob/CMakeLists.txt#L129-L130
- https://github.com/editorconfig/editorconfig-core-test/blob/5ca0b296dc31124d0303895c163013450bd97958/glob/braces.in#L10-L11

I'll clarify the spec.
