### ISSUE TITLE
Not work at all for FOO-mode!

### ISSUE THREAD

**Issue by dabrahams** [editorconfig/editorconfig-emacs#323]
where FOO=`cmake`.  As the doc says “Please feel free to submit issues if you find such modes,” well, here I am.  Please let me know if you need more information.

Thanks!

**Comment by xuhdev** [comment]
Could you provide more information? `cmake-mode` should have been supported: https://github.com/editorconfig/editorconfig-emacs/blob/4b81a5992858cbf03bcd7ed6ef31e4be0b55a7c1/editorconfig.el#L192

**Comment by dabrahams** [comment]
Huh. At least `fill-column` doesn't get set to the `.editorconfig`'s `max_line_length` until i invoke `editorconfig-apply` manually in CMake files.

**Comment by xuhdev** [comment]
Is `editorconfig-mode` on automatically when you open a CMake file? If not, could you double check whether you have properly set up the `editorconfig` extension (see [README](https://github.com/editorconfig/editorconfig-emacs?tab=readme-ov-file#getting-started))?

**Comment by dabrahams** [comment]
I can't reproduce the problem now; everything seems to be working.  Sorry for the noise!
