### ISSUE TITLE
Trying to contact "10sr"

### ISSUE THREAD

**Issue by monnier** [editorconfig/editorconfig-emacs#328]
We're trying to contact 10sr, the main author of the code, in order to clear its copyright for inclusion into Emacs.  They did not reply to my email.  Does someone here know how I could contact them?

**Comment by xuhdev** [comment]
Feel free to reply here if you still don't get any reply. Also feel free to let us know who else you need to.

I don't know the plan either 😅. I guess my copyright was cleared with FSF long time ago.

**Comment by 10sr** [comment]
@monnier Sorry recently I have not checked my mailbox... I'll check it before long 🙇 

@jcs090218 Thanks!

**Comment by 10sr** [comment]
I replied to the mail.
