### ISSUE TITLE
Visiting file in non-existent directory

### ISSUE THREAD

**Issue by greenrd** [editorconfig/editorconfig-emacs#35]
Before I installed editorconfig-emacs, visiting a file in a non-existent directory would work - I would then do M-x make-directory, as emacs prompted me to do, to create the directory. But now it does not work because an error appears in the modeline and the new buffer is not switched to.

Here is the backtrace:

```
Debugger entered--Lisp error: (file-error "Setting current directory" "no such file or directory" "/home/robin/foo/")
  call-process("editorconfig" nil "ecbuffer" nil "/home/robin/foo/bar")
  edconf-get-properties()
  edconf-find-file-hook()
  run-hooks(find-file-hook)
  after-find-file(t t)
  find-file-noselect-1(#<buffer bar> "~/foo/bar" nil nil "~/foo/bar" nil)
  find-file-noselect("/home/robin/foo/bar" nil nil t)
  find-file("/home/robin/foo/bar" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

**Comment by wlott** [comment]
This was bugging me too.  Enough that I fixed it.

https://github.com/editorconfig/editorconfig-emacs/pull/47
