### ISSUE TITLE
Cannot open load file: no such file or directory, editorconfig

### ISSUE THREAD

**Issue by aep-shoutlet** [editorconfig/editorconfig-emacs#36]
When I try to install the Emacs editorconfig plugin with Emacs Cask, I get an error.

Trace:

```
$ cask install
Cannot open load file: no such file or directory, editorconfig

$ which editorconfig
/usr/local/bin/editorconfig
```

Cask:

https://github.com/mcandre/dotfiles/blob/master/Cask

System:

```
specs cask emacs brew os
specs --version
0.20

cask --version
0.7.3

emacs --version
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

brew --version
0.9.5

system_profiler SPSoftwareDataType | grep 'System Version'
    System Software Overview:
      System Version: OS X 10.10.4 (14E46)
```

**Comment by xuhdev** [comment]
@aep-shoutlet I don't really think it means `editorconfig` binary, but some `cask` specific things... I'm not quite familiar with `cask`, do you know how `cask` knows what operation to do for a specific package when you use `cask install`?

**Comment by 10sr** [comment]
@aep-shoutlet There is a common trouble that Emacs cannot find executables that you can use from you shell, and there is already a package to solve this: https://github.com/purcell/exec-path-from-shell.
It happens a lot on Mac, and I think precisely it happens here.

TMK you have three options:

1. Do nothing: Currently this plugin works without Core-C (`editorconfig` executable)
2. If you want to use Core-C (we have more support for this),
  * Use :point_up: `exec-path-from-shell` package
  * Set `editorconfig-exec-path` to `"/usr/local/bin/editorconfig"` explicitly

**Comment by xuhdev** [comment]
Right, if you start Emacs in GUI mode by clicking on its icon, by default OS X does not append `/usr/local/bin` to the `PATH` environmental variable.

**Comment by mcandre** [comment]
xuhdev brings up an important edge case.

In my case, I'm using purely ncurses emacs from bash, with bash's PATH offering `/usr/local/bin` to emacs (so it could be editorconfig-mode's fault that something is ignoring the PATH information, e.g. hardcoding a path to the editorconfig binary).

**Comment by xuhdev** [comment]
@10sr Looks like the OP's issue is not related to `exec-path-from-shell`, although I don't know why...

**Comment by 10sr** [comment]
That's true... I mistook the text.
Umm... I just tried `cask install && cask emacs -Q`, I could start emacs and enable editorconfig-mode successfully.

I want to know the content of `Cask` file if the problem still occurs.

```
$ cask --version
0.8.1

$ emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.


$ system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: OS X 10.10.5 (14F2009)

```

**Comment by 10sr** [comment]
Closing because there are no update recently.
Please feel free to reopen issue if the problem still exists.
