### ISSUE TITLE
React to major mode changes

### ISSUE THREAD

**Issue by mbme** [editorconfig/editorconfig-emacs#38]
Currently variables are set only once -- after buffer is open. 
So if we switch buffer's major mode later editorconfig variables do not apply.

**Comment by xuhdev** [comment]
@mbme I tried to solve the problem in #44, but I got some unluck. Can you go to #44 to see the problem and briefly check what has happened? Thanks!

**Comment by rjhilgefort** [comment]
:+1:

**Comment by xuhdev** [comment]
Fixed in bade513e70bad12c494eef0ca47467767c9e93ff
