### ISSUE TITLE
customize variable widget disappears

### ISSUE THREAD

**Issue by thkoch2001** [editorconfig/editorconfig-emacs#40]
I open the customize-group 'editorconfig' and click the triangle next to 'Edconf Custom Hooks'. Then the whole widget disappears.
The `*Messages*` buffer says:
`widget-apply: Symbol's function definition is void: nil`

**Comment by 10sr** [comment]
I submitted a PR that should fix this.
I'd be glad if you try this branch :smiley_cat:

**Comment by 10sr** [comment]
I suppose this issue has been fixed now.
If you find it still remains, add comments here :-)
