### ISSUE TITLE
Don't depend on non-stable releases

### ISSUE THREAD

**Issue by cap10morgan** [editorconfig/editorconfig-emacs#52]
The latest release of editorconfig has [a non-stable dependency](https://github.com/editorconfig/editorconfig-emacs/blob/v0.6/editorconfig.el#L8) on editorconfig-core. This makes it not easy to install with only MELPA Stable.

**Comment by 10sr** [comment]
Thanks! :bow: 

I just released v0.6.1, which should fix this.

**Comment by cap10morgan** [comment]
Looks good, thank *you*!
