### ISSUE TITLE
Support for more programming language modes

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-emacs#58]
Please help editorconfig-emacs affect more programming language modes:

* Go
* Lua
* Tcl
* PostScript
* R
* `(setq-default tab-width (the-value-from-editorconfig-goes-here))`

**Comment by xuhdev** [comment]
@mcandre It would be nice if you can make a PR to achieve this---it is as easy as #53 (BTW, lua mode has been supported in the latest version).

**Comment by 10sr** [comment]
I'm now doing some investigations on these modes :smiley: 

* [x] Lua - Already supported
* [x] Go
  * I found that luckily we have already support for that, because go-mode always uses `tab-width` for indentation offset, right?

**Comment by xuhdev** [comment]
@10sr I think we need to explicitly set it for go... An ideal way would be asking the author of go mode to add a variable for indentation.

**Comment by 10sr** [comment]
@xuhdev You mean explicitly adding a list like `(go-mode . tab-width)` to editorconfig-indentation-alist ?

**Comment by xuhdev** [comment]
@10sr Yes, because `tab_width` in EditorConfig means a different thing than `indent_size`, as the way many Emacs major modes differentiate them.

**Comment by 10sr** [comment]
@xuhdev I see. Thanks!

**Comment by xuhdev** [comment]
@10sr However, I'm thinking about the case where `indent_size` and `tab_width` are both set---Emacs would be confused in this case, unfortunately. I would suggest to make a patch for go-mode to fix this issue and we can support the other modes first...

**Comment by 10sr** [comment]
Um... there is a bit difficult problem.
It seems that tab indent style is strongly recommended for golang.

I'm not sure if go-mode maintainers agree with the idea to add its own indent offset variable, because `go-mode` always enables tab indentation during its initialization ([here](https://github.com/dominikh/go-mode.el/blob/master/go-mode.el#L916)).
It is true that EditorConfig can overwrite this behavior so that space indentation will be used, but it is an unexpected situation for `go-mode`.
On the other hand I know we should support space indent style, too.

**Comment by xuhdev** [comment]
@10sr Maybe we should make an exception for golang, at least the major mode has a strong conflict with us... Also, we probably also have to make an exception for `Makefile`, the tab indent format?

**Comment by 10sr** [comment]
@xuhdev That makes sense to me.

**Comment by 10sr** [comment]
BTW, I would like to say that calling `setq-default` from EditorConfig is not a good idea: `setq-default` is for changing the Emacs default values, not buffer local ones.
Thus this can take effect on global Emacs configs including outside of the directories, which is not the desirable behavior as a EditorConfig plugin.

**Comment by mcandre** [comment]
> It seems that tab indent style is strongly recommended for golang.

Yep, gotta use hard tabs for Makefile and soft for **F#**.

https://github.com/mcandre/dotfiles/blob/master/.editorconfig

**Comment by 10sr** [comment]
@mcandre Yes, some languages have such limitations :innocent: 
So I suppose this plugin works as expected anyway for golang, is this right?
(I ask you because I'm not really familiar with golang)

**Comment by hensansi** [comment]
Can you add typescript-mode?

**Comment by 10sr** [comment]
@hensansi It is really easy to add a new language support (like #53 ) so it would be very nice if you can submit a PR for that :smile_cat:

**Comment by hensansi** [comment]
I just added nginx and typescript.
https://github.com/editorconfig/editorconfig-emacs/pull/67
