### ISSUE TITLE
Warn when .editorconfig invalid syntax

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-emacs#61]
The command line tool `editorconfig` reports when a path's `.editorconfig` file has a syntax error, which would prevent the style from taking effect.

In some of my own projects, I discovered that editorconfig-emacs silently fails to set a style when my `.editorconfig` file has syntax errors. Could we please show a warning (perhaps in the Emacs warning buffer) when this happens?

**Comment by 10sr** [comment]
Thanks!
I think that sounds like a good idea :+1:

**Comment by 10sr** [comment]
#65 :relaxed:
