### ISSUE TITLE
Support for matlab-mode, octave-mode

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-emacs#66]
Workaround:

```
(use-package matlab
             :config
             (setq matlab-indent-level tab-width
                   matlab-cont-level tab-width))
```

**Comment by xuhdev** [comment]
Thanks for the suggestion. Just to confirm, for octave-mode, is `octave-block-offset` the correct variable to set?

**Comment by mcandre** [comment]
@xuhdev Another is `octave-continuation-offset` for continuation indents (which some programmers want to do deeper than their ordinary indents). Does editorconfig / editorconfig-emacs have the ability to configure continuation indents?

**Comment by xuhdev** [comment]
@mcandre No, we don't do continuation, since the handling of line continuation varies across editors and is too language specific. However, you can add a setting in your Emacs configuration to force line continuation be set to the same as indentation offset.
