### ISSUE TITLE
final eol no longer respected

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-emacs#73]
# Summary

Emacs used to respect my final eol preference, but now it does nothing. My .bash_profile continues to save with no final eol, even though:

* I've configured .editorconfig to prefer final eol
* `require-final-newline` is `t`
* `mode-require-final-newline` is `t`

Additionally, whitespace-mode mistakenly highlights a final eol if I try to manually insert one.

Not sure if this a bug with editorconfig-emacs, emacs, or something else.

# Example

https://github.com/mcandre/dotfiles/blob/bashate/.bash_profile

# Configuration

https://github.com/mcandre/dotfiles/blob/bashate/.editorconfig

https://github.com/mcandre/dotfiles/blob/bashate/.emacs

https://github.com/mcandre/dotfiles/blob/bashate/Cask

# System

* GNU Emacs 24.5.1
* Homebrew
* El Capitan

**Comment by xuhdev** [comment]
Do you still have this issue after disabke editorconfig mode?

**Comment by mcandre** [comment]
Yes, issue persists when editorconfig-mode is disabled.

**Comment by xuhdev** [comment]
You probably want to disable other extensions to figure out what causes the issue...
