### ISSUE TITLE
Apply editorconfig settings to shebang'ed files sans extensions

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-emacs#75]
Please apply editorconfig settings such as `[{*.bash*}] indent_size = 4` to buffers that have an interpreter mode (shebang like `#!/bin/bash`), but no file extension (`post-merge-checkout-hook`).

**Comment by 10sr** [comment]
Thanks!
IMO we should discuss this in [editorconfig/editorconfig issue tracker](https://github.com/editorconfig/editorconfig/issues) instead of here :smiley:

**Comment by xuhdev** [comment]
Would a custom hook help here? I like the suggestion but I doubt whether it's easy to add it to the whole EditorConfig framework. But for Emacs, one should be able to write a custom hook for this.

**Comment by xuhdev** [comment]
Does custom hook solve your problem?

**Comment by 10sr** [comment]
Unn... I dont think custom hook wont work for this case.

A custom hook works *after* an editorconfig-core library is called, so there is no way to access properties under `[{*.bash*}]`, for this case, from custom hook...
I think we have to hack core libraries to get `indent_size = 4` for `#!/bin/bash` files.

**Comment by hlissner** [comment]
If it's any help to other Emacs users, I've used the following for the past couple of months with no issue:

<details>
  <summary>Expand code</summary>

```emacs-lisp
  ;; editorconfig cannot procure the correct settings for extension-less files.
  ;; Executable scripts with a shebang line, for example. So why not use Emacs'
  ;; major mode to drop editorconfig a hint? We temporarily append an extension
  ;; to `buffer-file-name' when talking to editorconfig.
  (defvar doom-editorconfig-mode-alist
    '((sh-mode     . "sh")
      (python-mode . "py")
      (ruby-mode   . "rb")
      (perl-mode   . "pl")
      (php-mode    . "php"))
    "An alist mapping major modes to extensions. Used by
`doom*editorconfig-smart-detection' to give editorconfig filetype hints.")

  (defun doom*editorconfig-smart-detection (orig-fn &rest args)
    "Retrieve the properties for the current file. If it doesn't have an
extension, try to guess one."
    (let ((buffer-file-name
           (if (file-name-extension buffer-file-name)
               buffer-file-name
             (format "%s%s" buffer-file-name
                     (let ((ext (cdr (assq major-mode doom-editorconfig-mode-alist))))
                       (or (and ext (concat "." ext))
                           ""))))))
      (apply orig-fn args)))
  (advice-add #'editorconfig-call-editorconfig-exec :around #'doom*editorconfig-smart-detection)
```

</details>

**Comment by cxw42** [comment]
See ongoing discussion in editorconfig/editorconfig#404

**Comment by 10sr** [comment]
Closing this, please proceed discussion in ☝️
