### ISSUE TITLE
How to disable editorconfig-mode for certain major modes?

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-emacs#76]
While waiting for #75, it would be useful to workaround editorconfig flaws with certain major modes, by disabling editorconfig when in those modes.

**Comment by mcandre** [comment]
Accomplished with

```
(add-hook 'sh-mode-hook
          (lambda ()
            (editorconfig-mode 0)))
```

**Comment by 10sr** [comment]
I think this will not work as expected... it will disable editorconfig "globally": properties will not be applied to any files opened after visiting sh-mode file.
I'll add a new variable for this.

**Comment by 10sr** [comment]
I've added a variable `editorconfig-exclude-modes` for this porpose :smile_cat:
