### ISSUE TITLE
Conflict with web-mode

### ISSUE THREAD

**Issue by choma** [editorconfig/editorconfig-emacs#79]
It seems that [this](https://github.com/editorconfig/editorconfig-emacs/pull/74) PR changed the way editorconfig and web-mode behaves together.
Now, when both of them are active, the `web-mode-block-padding` variable takes the value 4.
I've tested with [this .editorconfig](https://github.com/cakephp/cakephp/blob/master/.editorconfig) file from Cakephp project and this excerpt of my `init.el` file:
```elisp
;; Add package sources
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
						 ("marmalade" . "https://marmalade-repo.org/packages/")
						 ("melpa" . "https://melpa.org/packages/")
						 ))
(package-initialize)

(unless (package-installed-p 'use-package)
  (progn
	(package-refresh-contents)
	(package-install 'use-package)))
(setq use-package-verbose t)
(setq use-package-always-ensure t) ;; use :ensure t for all packages

(eval-when-compile
  (require 'use-package))

;; editorconfig (editorconfig.org)
(use-package editorconfig)
(editorconfig-mode 1)

;; web-mode (php,js,html,css)
(use-package web-mode)
```
Because of this, my php files indents like this:
```php
<?php
    class SomeClass {
        function some() {}
    }
```
Instead of this:
```php
<?php
class SomeClass {
    function some() {}
}
```
It gets fixed if I comment out `web-mode-block-padding` variable in editorconfig.el, but (since I'm an elisp newbie) I can't find the way to fix it on my init.el file.

**Comment by xuhdev** [comment]
In your particular example, I think you may want to report to `web-mode`, because `web-mode-block-padding` shouldn't indent the obvious `<?php`. @NdYAG What's your opinion?

**Comment by 10sr** [comment]
I think you can fix ad-hocly by adding the following to your init.el:

```
(add-hook 'editorconfig-custom-hooks
          (lambda (hash) (setq web-mode-block-padding 0)))
```

**Comment by choma** [comment]
Thanks! that worked!
I didn't know about `editorconfig-custom-hooks`, I know I should have read the code, but maybe it could be added to the readme.
On the other hand, do you think I should report this to web-mode too? I mean, won't this be fixed in editorconfig?

**Comment by 10sr** [comment]
> I didn't know about editorconfig-custom-hooks, I know I should have read the code, but maybe it could be added to the readme.

You are right :-) I'll add later, Thanks !

> On the other hand, do you think I should report this to web-mode too? I mean, won't this be fixed in editorconfig?

Unn... honestly I don't use web-mode so I have little idea what is the best approach for this :cry: 
One possible approach is to add `php` to [this list](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L6595), but I do not know whether this does not break anything.
Another is to add a code to check the filename when editorconfig.el sets indentation offsets and do not set `web-mode-block-padding` if the current file is a php file.

Anyway I want to wait for @NdYAG 's opinion, too.

**Comment by NdYAG** [comment]
Personally I think the above one is the right one indented

**Comment by choma** [comment]
@NdYAG, PSR-2 says the second is the [correct](http://www.php-fig.org/psr/psr-2/#1-1-example) one

**Comment by xuhdev** [comment]
Then I think it's probably an issueof web-mode : it should not indent after `<?php`

**Comment by choma** [comment]
It seems that `web-mode` has nothing to do with this. It was what I first thought since it works well (i.e. `web-mode-block-padding` is 0) when I don't use editorconfig.
I tried to read the code, but my elisp knowledge is pretty basic. If everybody agree that #74 is ok, then I think this issue can be closed. And maybe add the workaround to docs, since all php devs will need it.

**Comment by 10sr** [comment]
Well... I'm thinking how about reverting back the PR and removing `web-mode-block-padding` from editorconfig.el, because now I have an impression that its value is usually set to `0`.

@NdYAG What do you think of it?
When removed, you can still set `web-mode-block-padiing` by the following code:

```lisp
(add-to-list 'editorconfig-indentation-alist
     '(web-mode (web-mode-indent-style . (lambda (size) 2))
       web-mode-markup-indent-offset
       web-mode-css-indent-offset
       web-mode-code-indent-offset
       web-mode-block-padding
       web-mode-script-padding
       web-mode-style-padding))
```

**Comment by NdYAG** [comment]
@10sr The solution won't be convenient for those who code with multiple template languages.

If this value is 0 in most template language coding styles, then pls revert the PR.

**Comment by 10sr** [comment]
Thanks!
So, if there is no other opinion, I'm going to leave this as is and add a document including https://github.com/editorconfig/editorconfig-emacs/issues/79#issuecomment-200639230 tip.

**Comment by xuhdev** [comment]
@10sr More generally, we can add an instruction to tell users how to remove an entry in `editorconfig-indentation-alist`

**Comment by xuhdev** [comment]
Shall we close this issue?

**Comment by 10sr** [comment]
:ok_hand:

**Comment by NdYAG** [comment]
👍
The document clear it up. Thanks
