### ISSUE TITLE
A single quotation mark in comment would break the highlight

### ISSUE THREAD

**Issue by wangjiezhe** [editorconfig/editorconfig-emacs#83]
I have the word "Don't" in comment, and the highlight breaks down.

![](http://i.imgur.com/iWBFPVP.png)

**Comment by 10sr** [comment]
:scream: 
Thanks for reporting! I'll look into it!

**Comment by 10sr** [comment]
I think :point_up: PR fixes this issue.

**Comment by xuhdev** [comment]
@10sr The PR introduced another issue when the commenting character is `;`.

**Comment by wangjiezhe** [comment]
@10sr It does fix my problem.

**Comment by 10sr** [comment]
:(
