### ISSUE TITLE
Show what failed and where, when error parsing config file.

### ISSUE THREAD

**Issue by benf-wspdigital** [editorconfig/editorconfig-emacs#93]
Commit 74693c94e449ebbae77514464fe2ca1078a22e05 introduced a blunt error message when failing to parse the `.editorconfig` file:

> Error (editorconfig): Failed to parse file: …/.editorconfig.  Styles will not be applied.

This is better than no message. But it does not help the user know:
- What is the parsing error?
- If feasible, a suggestion of how that specific error can be corrected.
- What line of the file caused the parsing error?
- What was the text on that line which caused the error?

Please update the message to include that information.

**Comment by 10sr** [comment]
I submitted a PR:

* Changed error message slightly
* Show line number where error happened
* Show the text of the line

Contents of error messages will be like:

    Error (editorconfig): Error while reading config file: /home/a/editorconfig-emacs/.editorconfig:3:
        [ab
    .  Styles will not be applied.

It seems to require a bit more work to make a suggestion of how to fix the parse error, so it will be done in another PR 😇

**Comment by 10sr** [comment]
It seems that implementing code to suggest the way to fix errors is too difficult for its usefulness... 😓 
IMO the current message is enough for debugging .editorconfig files.
So closing this issue. Sorry!

**Comment by benf-wspdigital** [comment]
The change in commit 79a890c (released in (v0.7.8)[/editorconfig/editorconfig-emacs/releases/tag/v0.7.8]) addresses the main request here. Thank you!
