### ISSUE TITLE
By default Always Use Emacs Lisp Core when accessing files via tramp

### ISSUE THREAD

**Issue by 10sr** [editorconfig/editorconfig-emacs#98]
`editorconfig` external executables will not work for files accessed via tramp, OTOH Emacs Lisp core works in this case!

**Comment by xuhdev** [comment]
If this is the case, we can really consider changing the default. The main reason to use the C version is to maintain fewer versions of EditorConfig cores, but the benefit to edit remote files is cool. Have you tested the speed in a slow connection environment?

However, in any case, we should leave the choice to the user, no matter what we use as the default.

**Comment by 10sr** [comment]
To be honest, I've not tried this at all yet :sweat: I just read an user wrote about this.
I'll try this shortly. Testing under a poor network is a good idea!

> However, in any case, we should leave the choice to the user, no matter what we use as the default.

I agree :raising_hand: 
To be precise, I'm planning to change the default behavior.
