### ISSUE TITLE
error loading editorconfig on osx 

### ISSUE THREAD

**Issue by sburke56** [editorconfig/editorconfig-emacs#99]
I'm not sure what this error is trying to tell me. 

**Error (editorconfig): Symbol's function definition is void: editorconfig-core-get-properties-hash.  Styles will not be applied.**

I have Emacs 24.5.1 binary distribution for OSX.  I installed editorconfig with brew.  And I am having the same issue whether I click on the icon or run emacs from a terminal.  

Any help would be appreciated.

**Comment by 10sr** [comment]
Umm... how did you install this plugin?

**Comment by sburke56** [comment]
I cloned the repo and added *.el to my elisp directory which is in my load
path. Is that correct?

**Comment by 10sr** [comment]
I see.
I've just submitted and merged a fix for this.
Could you pull the master branch and try again?

**Comment by sburke56** [comment]
I pulled the fix & it seems to be working.  I'm not getting the error any
more when I open a code file.  Thanks for the quick fix.

On Thu, Jun 23, 2016 at 11:48 PM, 10sr <notifications@github.com> wrote:

> I see.
> I've just submitted and merged a fix for this.
> Could you pull the master branch and try again?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/editorconfig/editorconfig-emacs/issues/99#issuecomment-228251924>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AANL47llMJSsYUf-XDgS0m_SX6H7Mywcks5qO1OCgaJpZM4I9LZP>
> .
>



-- 
Steve
www.stayathomedevs.com
GDEOnline.solutions
Game Data Editor Unity Plugin
<https://www.assetstore.unity3d.com/en/#!/content/18480>

**Comment by 10sr** [comment]
👍 
Closing.
